### ISSUE TITLE
blocks websites

### ISSUE THREAD

**Issue by YehiaWLD** [Abdelrahmanthecoder/Blob-Ad-blocker#1]
all of the listed websites in [background.js](https://github.com/Abdelrahmanthecoder/Blob-Ad-blocker/blob/main/background.js)
are blocked from entering and some of the sites there are pretty major like (wix.com, goddady etc.)
it is a very inefficient way of blocking ads. as it blocks you from viewing the site.
 

### SUGGESTIONS 
 add support for a ui to turn it on and off
and support for video ads on broadcasting sites such as youtube.

**great extension tho keep up the good  work**
_there is room for improvement_

**Comment by Abdelrahmanthecoder** [comment]
Ok thank you for the comment, i will get to work as soon as possible and fix the issues

**Comment by YehiaWLD** [comment]
Great glad to hear!
