### ISSUE TITLE
manfiest

### ISSUE THREAD

**Issue by YehiaWLD** [Abdelrahmanthecoder/Blob-Ad-blocker#2]
this is a small issue but change the "manifest_version" from 2 to 1 as it causes errors

**Comment by Abdelrahmanthecoder** [comment]
Yes mr, thank you for the comment, once google fully releases manifest V3 we will migrate, but for now there is nothing we can do. And the manifest_version needs to go from 2 to 3 not 2 to 1. Anyways thanks for mentioning it!
